version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  user_event_receiver:
    image: user-event-receiver
    container_name: user-event-receiver-app
    build:
      context: ./user-event-receiver/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
  user_event_processor:
    image: user-event-processor
    container_name: user-event-processor-app
    build:
      context: ./user-event-processor
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    environment:
      - SPRING_RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq