// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_event.proto

package com.konux.usereventprocessor.amqp.event;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020user_event.proto\"s\n\tUserEvent\022\026\n\ttimes" +
      "tamp\030\001 \001(\003H\000\210\001\001\022\023\n\006userId\030\002 \001(\003H\001\210\001\001\022\024\n\007" +
      "message\030\003 \001(\tH\002\210\001\001B\014\n\n_timestampB\t\n\007_use" +
      "rIdB\n\n\010_messageB2\n\'com.konux.usereventpr" +
      "ocessor.amqp.eventB\005EventP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserEvent_descriptor,
        new java.lang.String[] { "Timestamp", "UserId", "Message", "Timestamp", "UserId", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
