// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_event.proto

package com.konux.usereventprocessor.amqp.event;

public interface UserEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>optional int64 userId = 2;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>optional string message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
