server:
  port: @user-message-receiver-server.port@
  servlet:
    context-path: @server.servlet.context-path@
spring:
  rabbitmq:
    username: @rabbit.username@
    password: @rabbit.password@
    host: @rabbit.hostname@
    port: @rabbit.port@
    template:
      routing-key: @rabbit.user-events.routing-key@
      exchange: @rabbit.user-events.exchange@
      retry:
        enabled: @rabbit.retry.enabled@
        max-attempts: @rabbit.max-attempts@
        max-interval: @rabbit.max-interval@
    publisher-returns: true
    publisher-confirm-type: simple